name: build-push-latex
on:
  push:
    branches:
      - master
    paths-ignore:
    - '**.md'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: build-latex
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: .github/latex-build.sh